// Mock weather data keyed by city id. Replace with API integration later.
export const MOCK_WEATHER = {
    krakow: {
        city: 'Kraków',
        country: 'Poland',
        currentTempC: 18,
        condition: 'Partly Cloudy',
        icon: '⛅️',
        precipitation: {probability: 20, type: 'rain', amountMm: 0.8},
        wind: {speedKph: 14, direction: 'NW'},
        cloudiness: 45,
        forecast: [
            {day: 'Mon', tempC: 17, condition: 'Cloudy', icon: '☁️'},
            {day: 'Tue', tempC: 19, condition: 'Sunny', icon: '☀️'},
            {day: 'Wed', tempC: 18, condition: 'Light Rain', icon: '🌦️'},
            {day: 'Thu', tempC: 16, condition: 'Rain', icon: '🌧️'},
            {day: 'Fri', tempC: 15, condition: 'Windy', icon: '💨'},
            {day: 'Fri', tempC: 15, condition: 'Windy', icon: '💨'},
            {day: 'Fri', tempC: 15, condition: 'Windy', icon: '💨'},
            {day: 'Fri', tempC: 15, condition: 'Windy', icon: '💨'},
            {day: 'Fri', tempC: 15, condition: 'Windy', icon: '💨'},
            {day: 'Fri', tempC: 15, condition: 'Windy', icon: '💨'},
            {day: 'Fri', tempC: 15, condition: 'Windy', icon: '💨'},

        ],
    },
    warsaw: {
        city: 'Warsaw',
        country: 'Poland',
        currentTempC: 20,
        condition: 'Sunny',
        icon: '☀️',
        precipitation: {probability: 5, type: 'none', amountMm: 0},
        wind: {speedKph: 9, direction: 'E'},
        cloudiness: 10,
        forecast: [
            {day: 'Mon', tempC: 21, condition: 'Sunny', icon: '☀️'},
            {day: 'Tue', tempC: 22, condition: 'Sunny', icon: '☀️'},
            {day: 'Wed', tempC: 19, condition: 'Partly Cloudy', icon: '⛅️'},
            {day: 'Thu', tempC: 18, condition: 'Cloudy', icon: '☁️'},
            {day: 'Fri', tempC: 20, condition: 'Sunny', icon: '☀️'},
        ],
    },
    berlin: {
        city: 'Berlin',
        country: 'Germany',
        currentTempC: 16,
        condition: 'Light Rain',
        icon: '🌦️',
        precipitation: {probability: 60, type: 'rain', amountMm: 3.2},
        wind: {speedKph: 18, direction: 'W'},
        cloudiness: 70,
        forecast: [
            {day: 'Mon', tempC: 16, condition: 'Light Rain', icon: '🌦️'},
            {day: 'Tue', tempC: 15, condition: 'Rain', icon: '🌧️'},
            {day: 'Wed', tempC: 16, condition: 'Cloudy', icon: '☁️'},
            {day: 'Thu', tempC: 17, condition: 'Partly Cloudy', icon: '⛅️'},
            {day: 'Fri', tempC: 18, condition: 'Sunny', icon: '☀️'},
        ],
    },
    prague: {
        city: 'Prague',
        country: 'Czechia',
        currentTempC: 17,
        condition: 'Cloudy',
        icon: '☁️',
        precipitation: {probability: 30, type: 'rain', amountMm: 1.5},
        wind: {speedKph: 12, direction: 'NE'},
        cloudiness: 60,
        forecast: [
            {day: 'Mon', tempC: 17, condition: 'Cloudy', icon: '☁️'},
            {day: 'Tue', tempC: 18, condition: 'Cloudy', icon: '☁️'},
            {day: 'Wed', tempC: 19, condition: 'Partly Cloudy', icon: '⛅️'},
            {day: 'Thu', tempC: 18, condition: 'Light Rain', icon: '🌦️'},
            {day: 'Fri', tempC: 17, condition: 'Cloudy', icon: '☁️'},
        ],
    },
    vienna: {
        city: 'Vienna',
        country: 'Austria',
        currentTempC: 19,
        condition: 'Windy',
        icon: '💨',
        precipitation: {probability: 10, type: 'none', amountMm: 0},
        wind: {speedKph: 24, direction: 'N'},
        cloudiness: 35,
        forecast: [
            {day: 'Mon', tempC: 19, condition: 'Windy', icon: '💨'},
            {day: 'Tue', tempC: 18, condition: 'Partly Cloudy', icon: '⛅️'},
            {day: 'Wed', tempC: 18, condition: 'Cloudy', icon: '☁️'},
            {day: 'Thu', tempC: 17, condition: 'Light Rain', icon: '🌦️'},
            {day: 'Fri', tempC: 20, condition: 'Sunny', icon: '☀️'},
        ],
    },
    budapest: {
        city: 'Budapest',
        country: 'Hungary',
        currentTempC: 21,
        condition: 'Sunny',
        icon: '☀️',
        precipitation: {probability: 10, type: 'none', amountMm: 0},
        wind: {speedKph: 8, direction: 'SE'},
        cloudiness: 12,
        forecast: [
            {day: 'Mon', tempC: 21, condition: 'Sunny', icon: '☀️'},
            {day: 'Tue', tempC: 22, condition: 'Sunny', icon: '☀️'},
            {day: 'Wed', tempC: 21, condition: 'Partly Cloudy', icon: '⛅️'},
            {day: 'Thu', tempC: 20, condition: 'Cloudy', icon: '☁️'},
            {day: 'Fri', tempC: 19, condition: 'Rain', icon: '🌧️'},
        ],
    },
    london: {
        city: 'London',
        country: 'United Kingdom',
        currentTempC: 15,
        condition: 'Drizzle',
        icon: '🌧️',
        precipitation: {probability: 70, type: 'rain', amountMm: 4.1},
        wind: {speedKph: 22, direction: 'SW'},
        cloudiness: 85,
        forecast: [
            {day: 'Mon', tempC: 15, condition: 'Drizzle', icon: '🌧️'},
            {day: 'Tue', tempC: 14, condition: 'Rain', icon: '🌧️'},
            {day: 'Wed', tempC: 15, condition: 'Cloudy', icon: '☁️'},
            {day: 'Thu', tempC: 16, condition: 'Partly Cloudy', icon: '⛅️'},
            {day: 'Fri', tempC: 17, condition: 'Sunny', icon: '☀️'},
        ],
    },
    paris: {
        city: 'Paris',
        country: 'France',
        currentTempC: 18,
        condition: 'Partly Cloudy',
        icon: '⛅️',
        precipitation: {probability: 15, type: 'rain', amountMm: 0.4},
        wind: {speedKph: 10, direction: 'N'},
        cloudiness: 40,
        forecast: [
            {day: 'Mon', tempC: 18, condition: 'Partly Cloudy', icon: '⛅️'},
            {day: 'Tue', tempC: 19, condition: 'Sunny', icon: '☀️'},
            {day: 'Wed', tempC: 18, condition: 'Cloudy', icon: '☁️'},
            {day: 'Thu', tempC: 17, condition: 'Light Rain', icon: '🌦️'},
            {day: 'Fri', tempC: 18, condition: 'Partly Cloudy', icon: '⛅️'},
        ],
    },
};
