// Mock weather data keyed by city id. Replace with API integration later.
export const MOCK_WEATHER = {
    krakow: {
        city: 'Kraków',
        country: 'Poland',
        currentTempC: 18,
        condition: 'Partly Cloudy',
        icon: '⛅️',
        precipitation: {probability: 20, type: 'rain', amountMm: 0.8},
        wind: {speedKph: 14, direction: 'NW'},
        cloudiness: 45,
        forecast: [
            {
                day: 'Mon',
                tempC: 17,
                condition: 'Cloudy',
                icon: '☁️',
                windDirection: 'NW',
                precipitationMm: 0.6,
                precipitationType: 'rain',
                cloudCover: 72,
            },
            {
                day: 'Tue',
                tempC: 19,
                condition: 'Sunny',
                icon: '☀️',
                windDirection: 'NW',
                precipitationMm: 0,
                precipitationType: 'none',
                cloudCover: 18,
            },
            {
                day: 'Wed',
                tempC: 18,
                condition: 'Light Rain',
                icon: '🌦️',
                windDirection: 'W',
                precipitationMm: 1.4,
                precipitationType: 'rain',
                cloudCover: 68,
            },
            {
                day: 'Thu',
                tempC: 16,
                condition: 'Rain',
                icon: '🌧️',
                windDirection: 'WNW',
                precipitationMm: 3.1,
                precipitationType: 'rain',
                cloudCover: 92,
            },
            {
                day: 'Fri',
                tempC: 15,
                condition: 'Windy',
                icon: '💨',
                windDirection: 'N',
                precipitationMm: 0.2,
                precipitationType: 'rain',
                cloudCover: 36,
            },
            {
                day: 'Sat',
                tempC: 14,
                condition: 'Showers',
                icon: '🌦️',
                windDirection: 'NNW',
                precipitationMm: 2.4,
                precipitationType: 'rain',
                cloudCover: 78,
            },
            {
                day: 'Sun',
                tempC: 17,
                condition: 'Partly Cloudy',
                icon: '⛅️',
                windDirection: 'NW',
                precipitationMm: 0.4,
                precipitationType: 'rain',
                cloudCover: 48,
            },
            {
                day: 'Mon+',
                tempC: 20,
                condition: 'Sunny',
                icon: '☀️',
                windDirection: 'W',
                precipitationMm: 0,
                precipitationType: 'none',
                cloudCover: 20,
            },
        ],
    },
    warsaw: {
        city: 'Warsaw',
        country: 'Poland',
        currentTempC: 20,
        condition: 'Sunny',
        icon: '☀️',
        precipitation: {probability: 5, type: 'none', amountMm: 0},
        wind: {speedKph: 9, direction: 'E'},
        cloudiness: 10,
        forecast: [
            {
                day: 'Mon',
                tempC: 21,
                condition: 'Sunny',
                icon: '☀️',
                windDirection: 'E',
                precipitationMm: 0,
                precipitationType: 'none',
                cloudCover: 12,
            },
            {
                day: 'Tue',
                tempC: 22,
                condition: 'Sunny',
                icon: '☀️',
                windDirection: 'E',
                precipitationMm: 0,
                precipitationType: 'none',
                cloudCover: 10,
            },
            {
                day: 'Wed',
                tempC: 19,
                condition: 'Partly Cloudy',
                icon: '⛅️',
                windDirection: 'ENE',
                precipitationMm: 0.3,
                precipitationType: 'rain',
                cloudCover: 35,
            },
            {
                day: 'Thu',
                tempC: 18,
                condition: 'Cloudy',
                icon: '☁️',
                windDirection: 'E',
                precipitationMm: 0.6,
                precipitationType: 'rain',
                cloudCover: 60,
            },
            {
                day: 'Fri',
                tempC: 20,
                condition: 'Sunny',
                icon: '☀️',
                windDirection: 'ESE',
                precipitationMm: 0,
                precipitationType: 'none',
                cloudCover: 8,
            },
            {
                day: 'Sat',
                tempC: 21,
                condition: 'Sunny',
                icon: '☀️',
                windDirection: 'E',
                precipitationMm: 0,
                precipitationType: 'none',
                cloudCover: 12,
            },
            {
                day: 'Sun',
                tempC: 20,
                condition: 'Partly Cloudy',
                icon: '⛅️',
                windDirection: 'ESE',
                precipitationMm: 0.2,
                precipitationType: 'rain',
                cloudCover: 28,
            },
            {
                day: 'Mon+',
                tempC: 22,
                condition: 'Sunny',
                icon: '☀️',
                windDirection: 'E',
                precipitationMm: 0,
                precipitationType: 'none',
                cloudCover: 10,
            },
        ],
    },
    berlin: {
        city: 'Berlin',
        country: 'Germany',
        currentTempC: 16,
        condition: 'Light Rain',
        icon: '🌦️',
        precipitation: {probability: 60, type: 'rain', amountMm: 3.2},
        wind: {speedKph: 18, direction: 'W'},
        cloudiness: 70,
        forecast: [
            {
                day: 'Mon',
                tempC: 16,
                condition: 'Light Rain',
                icon: '🌦️',
                windDirection: 'W',
                precipitationMm: 2.1,
                precipitationType: 'rain',
                cloudCover: 78,
            },
            {
                day: 'Tue',
                tempC: 15,
                condition: 'Rain',
                icon: '🌧️',
                windDirection: 'WSW',
                precipitationMm: 4.2,
                precipitationType: 'rain',
                cloudCover: 90,
            },
            {
                day: 'Wed',
                tempC: 16,
                condition: 'Cloudy',
                icon: '☁️',
                windDirection: 'W',
                precipitationMm: 0.5,
                precipitationType: 'rain',
                cloudCover: 72,
            },
            {
                day: 'Thu',
                tempC: 17,
                condition: 'Partly Cloudy',
                icon: '⛅️',
                windDirection: 'WNW',
                precipitationMm: 0.2,
                precipitationType: 'rain',
                cloudCover: 48,
            },
            {
                day: 'Fri',
                tempC: 18,
                condition: 'Sunny',
                icon: '☀️',
                windDirection: 'W',
                precipitationMm: 0,
                precipitationType: 'none',
                cloudCover: 18,
            },
            {
                day: 'Sat',
                tempC: 19,
                condition: 'Partly Cloudy',
                icon: '⛅️',
                windDirection: 'WSW',
                precipitationMm: 0.3,
                precipitationType: 'rain',
                cloudCover: 32,
            },
            {
                day: 'Sun',
                tempC: 18,
                condition: 'Cloudy',
                icon: '☁️',
                windDirection: 'W',
                precipitationMm: 0.5,
                precipitationType: 'rain',
                cloudCover: 60,
            },
            {
                day: 'Mon+',
                tempC: 20,
                condition: 'Sunny',
                icon: '☀️',
                windDirection: 'W',
                precipitationMm: 0,
                precipitationType: 'none',
                cloudCover: 22,
            },
        ],
    },
    prague: {
        city: 'Prague',
        country: 'Czechia',
        currentTempC: 17,
        condition: 'Cloudy',
        icon: '☁️',
        precipitation: {probability: 30, type: 'rain', amountMm: 1.5},
        wind: {speedKph: 12, direction: 'NE'},
        cloudiness: 60,
        forecast: [
            {
                day: 'Mon',
                tempC: 17,
                condition: 'Cloudy',
                icon: '☁️',
                windDirection: 'NE',
                precipitationMm: 0.8,
                precipitationType: 'rain',
                cloudCover: 70,
            },
            {
                day: 'Tue',
                tempC: 18,
                condition: 'Cloudy',
                icon: '☁️',
                windDirection: 'NE',
                precipitationMm: 0.6,
                precipitationType: 'rain',
                cloudCover: 68,
            },
            {
                day: 'Wed',
                tempC: 19,
                condition: 'Partly Cloudy',
                icon: '⛅️',
                windDirection: 'ENE',
                precipitationMm: 0.2,
                precipitationType: 'rain',
                cloudCover: 40,
            },
            {
                day: 'Thu',
                tempC: 18,
                condition: 'Light Rain',
                icon: '🌦️',
                windDirection: 'NE',
                precipitationMm: 1.2,
                precipitationType: 'rain',
                cloudCover: 76,
            },
            {
                day: 'Fri',
                tempC: 17,
                condition: 'Cloudy',
                icon: '☁️',
                windDirection: 'NNE',
                precipitationMm: 0.5,
                precipitationType: 'rain',
                cloudCover: 65,
            },
            {
                day: 'Sat',
                tempC: 16,
                condition: 'Light Rain',
                icon: '🌦️',
                windDirection: 'NE',
                precipitationMm: 1.6,
                precipitationType: 'rain',
                cloudCover: 82,
            },
            {
                day: 'Sun',
                tempC: 18,
                condition: 'Partly Cloudy',
                icon: '⛅️',
                windDirection: 'ENE',
                precipitationMm: 0.3,
                precipitationType: 'rain',
                cloudCover: 44,
            },
            {
                day: 'Mon+',
                tempC: 19,
                condition: 'Sunny',
                icon: '☀️',
                windDirection: 'E',
                precipitationMm: 0,
                precipitationType: 'none',
                cloudCover: 20,
            },
        ],
    },
    vienna: {
        city: 'Vienna',
        country: 'Austria',
        currentTempC: 19,
        condition: 'Windy',
        icon: '💨',
        precipitation: {probability: 10, type: 'none', amountMm: 0},
        wind: {speedKph: 24, direction: 'N'},
        cloudiness: 35,
        forecast: [
            {
                day: 'Mon',
                tempC: 19,
                condition: 'Windy',
                icon: '💨',
                windDirection: 'N',
                precipitationMm: 0,
                precipitationType: 'none',
                cloudCover: 30,
            },
            {
                day: 'Tue',
                tempC: 18,
                condition: 'Partly Cloudy',
                icon: '⛅️',
                windDirection: 'NNE',
                precipitationMm: 0.2,
                precipitationType: 'rain',
                cloudCover: 42,
            },
            {
                day: 'Wed',
                tempC: 18,
                condition: 'Cloudy',
                icon: '☁️',
                windDirection: 'N',
                precipitationMm: 0.4,
                precipitationType: 'rain',
                cloudCover: 64,
            },
            {
                day: 'Thu',
                tempC: 17,
                condition: 'Light Rain',
                icon: '🌦️',
                windDirection: 'NNW',
                precipitationMm: 1.6,
                precipitationType: 'rain',
                cloudCover: 78,
            },
            {
                day: 'Fri',
                tempC: 20,
                condition: 'Sunny',
                icon: '☀️',
                windDirection: 'N',
                precipitationMm: 0,
                precipitationType: 'none',
                cloudCover: 20,
            },
            {
                day: 'Sat',
                tempC: 21,
                condition: 'Sunny',
                icon: '☀️',
                windDirection: 'N',
                precipitationMm: 0,
                precipitationType: 'none',
                cloudCover: 22,
            },
            {
                day: 'Sun',
                tempC: 20,
                condition: 'Partly Cloudy',
                icon: '⛅️',
                windDirection: 'NNE',
                precipitationMm: 0.3,
                precipitationType: 'rain',
                cloudCover: 30,
            },
            {
                day: 'Mon+',
                tempC: 22,
                condition: 'Sunny',
                icon: '☀️',
                windDirection: 'N',
                precipitationMm: 0,
                precipitationType: 'none',
                cloudCover: 18,
            },
        ],
    },
    budapest: {
        city: 'Budapest',
        country: 'Hungary',
        currentTempC: 21,
        condition: 'Sunny',
        icon: '☀️',
        precipitation: {probability: 10, type: 'none', amountMm: 0},
        wind: {speedKph: 8, direction: 'SE'},
        cloudiness: 12,
        forecast: [
            {
                day: 'Mon',
                tempC: 21,
                condition: 'Sunny',
                icon: '☀️',
                windDirection: 'SE',
                precipitationMm: 0,
                precipitationType: 'none',
                cloudCover: 10,
            },
            {
                day: 'Tue',
                tempC: 22,
                condition: 'Sunny',
                icon: '☀️',
                windDirection: 'SE',
                precipitationMm: 0,
                precipitationType: 'none',
                cloudCover: 12,
            },
            {
                day: 'Wed',
                tempC: 21,
                condition: 'Partly Cloudy',
                icon: '⛅️',
                windDirection: 'SSE',
                precipitationMm: 0.4,
                precipitationType: 'rain',
                cloudCover: 38,
            },
            {
                day: 'Thu',
                tempC: 20,
                condition: 'Cloudy',
                icon: '☁️',
                windDirection: 'SE',
                precipitationMm: 0.8,
                precipitationType: 'rain',
                cloudCover: 62,
            },
            {
                day: 'Fri',
                tempC: 19,
                condition: 'Rain',
                icon: '🌧️',
                windDirection: 'SSE',
                precipitationMm: 2.4,
                precipitationType: 'rain',
                cloudCover: 85,
            },
            {
                day: 'Sat',
                tempC: 18,
                condition: 'Cloudy',
                icon: '☁️',
                windDirection: 'SE',
                precipitationMm: 0.6,
                precipitationType: 'rain',
                cloudCover: 70,
            },
            {
                day: 'Sun',
                tempC: 20,
                condition: 'Partly Cloudy',
                icon: '⛅️',
                windDirection: 'ESE',
                precipitationMm: 0.2,
                precipitationType: 'rain',
                cloudCover: 38,
            },
            {
                day: 'Mon+',
                tempC: 21,
                condition: 'Sunny',
                icon: '☀️',
                windDirection: 'SE',
                precipitationMm: 0,
                precipitationType: 'none',
                cloudCover: 16,
            },
        ],
    },
    london: {
        city: 'London',
        country: 'United Kingdom',
        currentTempC: 15,
        condition: 'Drizzle',
        icon: '🌧️',
        precipitation: {probability: 70, type: 'rain', amountMm: 4.1},
        wind: {speedKph: 22, direction: 'SW'},
        cloudiness: 85,
        forecast: [
            {
                day: 'Mon',
                tempC: 15,
                condition: 'Drizzle',
                icon: '🌧️',
                windDirection: 'SW',
                precipitationMm: 3.1,
                precipitationType: 'rain',
                cloudCover: 90,
            },
            {
                day: 'Tue',
                tempC: 14,
                condition: 'Rain',
                icon: '🌧️',
                windDirection: 'SW',
                precipitationMm: 5,
                precipitationType: 'rain',
                cloudCover: 94,
            },
            {
                day: 'Wed',
                tempC: 15,
                condition: 'Cloudy',
                icon: '☁️',
                windDirection: 'SW',
                precipitationMm: 0.7,
                precipitationType: 'rain',
                cloudCover: 82,
            },
            {
                day: 'Thu',
                tempC: 16,
                condition: 'Partly Cloudy',
                icon: '⛅️',
                windDirection: 'SSW',
                precipitationMm: 0.3,
                precipitationType: 'rain',
                cloudCover: 55,
            },
            {
                day: 'Fri',
                tempC: 17,
                condition: 'Sunny',
                icon: '☀️',
                windDirection: 'SW',
                precipitationMm: 0,
                precipitationType: 'none',
                cloudCover: 28,
            },
            {
                day: 'Sat',
                tempC: 16,
                condition: 'Partly Cloudy',
                icon: '⛅️',
                windDirection: 'SW',
                precipitationMm: 0.4,
                precipitationType: 'rain',
                cloudCover: 52,
            },
            {
                day: 'Sun',
                tempC: 18,
                condition: 'Sunny',
                icon: '☀️',
                windDirection: 'SSW',
                precipitationMm: 0,
                precipitationType: 'none',
                cloudCover: 24,
            },
            {
                day: 'Mon+',
                tempC: 19,
                condition: 'Sunny',
                icon: '☀️',
                windDirection: 'SW',
                precipitationMm: 0,
                precipitationType: 'none',
                cloudCover: 18,
            },
        ],
    },
    paris: {
        city: 'Paris',
        country: 'France',
        currentTempC: 18,
        condition: 'Partly Cloudy',
        icon: '⛅️',
        precipitation: {probability: 15, type: 'rain', amountMm: 0.4},
        wind: {speedKph: 10, direction: 'N'},
        cloudiness: 40,
        forecast: [
            {
                day: 'Mon',
                tempC: 18,
                condition: 'Partly Cloudy',
                icon: '⛅️',
                windDirection: 'N',
                precipitationMm: 0.2,
                precipitationType: 'rain',
                cloudCover: 50,
            },
            {
                day: 'Tue',
                tempC: 19,
                condition: 'Sunny',
                icon: '☀️',
                windDirection: 'NNE',
                precipitationMm: 0,
                precipitationType: 'none',
                cloudCover: 18,
            },
            {
                day: 'Wed',
                tempC: 18,
                condition: 'Cloudy',
                icon: '☁️',
                windDirection: 'N',
                precipitationMm: 0.6,
                precipitationType: 'rain',
                cloudCover: 70,
            },
            {
                day: 'Thu',
                tempC: 17,
                condition: 'Light Rain',
                icon: '🌦️',
                windDirection: 'NNW',
                precipitationMm: 1.1,
                precipitationType: 'rain',
                cloudCover: 78,
            },
            {
                day: 'Fri',
                tempC: 18,
                condition: 'Partly Cloudy',
                icon: '⛅️',
                windDirection: 'N',
                precipitationMm: 0.3,
                precipitationType: 'rain',
                cloudCover: 45,
            },
            {
                day: 'Sat',
                tempC: 19,
                condition: 'Sunny',
                icon: '☀️',
                windDirection: 'NNE',
                precipitationMm: 0,
                precipitationType: 'none',
                cloudCover: 22,
            },
            {
                day: 'Sun',
                tempC: 17,
                condition: 'Cloudy',
                icon: '☁️',
                windDirection: 'NNW',
                precipitationMm: 0.7,
                precipitationType: 'rain',
                cloudCover: 66,
            },
            {
                day: 'Mon+',
                tempC: 20,
                condition: 'Sunny',
                icon: '☀️',
                windDirection: 'N',
                precipitationMm: 0,
                precipitationType: 'none',
                cloudCover: 18,
            },
        ],
    },
};
